connection-string-tracking
snowflakedb/snowflake-connector-python pull request #1002
Opened 2021-12-09 22:01 UTC by sfc-gh-madkins

This is an enhancement to the python connector to allow snowflake to track partner driven consumption by searching for a partner defined environment variable in circumstances where a partner provides managed infrastructure, but a customer manual downloads the connector via pip.

2022-02-03 21:36 UTC, sfc-gh-mkeller requested changes
This also needs a test, someone should add one

2022-02-03 21:36 UTC, sfc-gh-mkeller commented on src/snowflake/connector/connection.py
> +    "application": (os.environ.get('SNOWFLAKE_PARTNER', CLIENT_NAME), (type(None), str)),
We usually prefix env variables with `SF_`, let's keep to that.
```suggestion
    "application": (os.environ.get('SF_PARTNER', CLIENT_NAME), (type(None), str)),
```

2022-02-04 23:52 UTC, sfc-gh-mkeller requested changes

2022-02-04 23:52 UTC, sfc-gh-mkeller commented on src/snowflake/connector/constants.py
> +ENV_VAR_PARTNER = "SNOWFLAKE_PARTNER"
Same as what I said before @sfc-gh-madkins
```suggestion
ENV_VAR_PARTNER = "SF_PARTNER"
```

2022-02-07 00:41 UTC, sfc-gh-madkins commented
I have read the CLA Document and I hereby sign the CLA

2022-02-14 22:08 UTC, sfc-gh-mkeller approved these changes
![](https://i.fluffy.cc/hc8WTNRNffFv0fTPJDTdFFbsKMCQn5Rz.gif)

2022-02-14 22:08 UTC, merged