SNOW-518496: Bumped up PythonConnector PATCH version from 2.7.1 to 2.7.2
snowflakedb/snowflake-connector-python pull request #1006
Opened 2021-12-14 22:27 UTC by sfc-gh-kdama

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #NNNN

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

2021-12-15 00:08 UTC, sfc-gh-mkeller approved these changes

2021-12-15 22:18 UTC, sfc-gh-mkeller requested changes

2021-12-15 22:18 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
> +Release Notes
Oh this changed:
```suggestion
# Release Notes
```

2021-12-15 22:19 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
> +-------------------------------------------------------------------------------
```suggestion
```

2021-12-15 22:20 UTC, sfc-gh-mkeller approved these changes

2021-12-16 20:03 UTC, sfc-gh-kdama commented
I have read the CLA Document and I hereby sign the CLA

2021-12-16 21:45 UTC, merged