SNOW-499493 Add Interval Precision to Timestamp
snowflakedb/snowflake-connector-python pull request #1030
Opened 2022-01-13 21:49 UTC by sfc-gh-jbahk

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes SNOW-499493

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

2022-01-21 20:08 UTC, sfc-gh-mkeller requested changes

2022-01-21 20:08 UTC, sfc-gh-mkeller commented on src/snowflake/connector/arrow_context.py
> +    def TIMESTAMP_LTZ_to_python_one_field(self, microseconds):
Missing return type-hint and confusing name

2022-01-21 20:08 UTC, sfc-gh-mkeller commented on src/snowflake/connector/arrow_context.py
> +    def TIMESTAMP_LTZ_to_python_two_field(self, epoch: float, fraction: float):
Please add a return type-hint and change the name of this function to something that describes how this is different from the other function

2022-01-21 20:08 UTC, sfc-gh-mkeller commented on src/snowflake/connector/arrow_context.py
> +    def TIMESTAMP_LTZ_to_python_one_field_windows(self, microseconds):
Add type-hints and maybe a doc-string that describes why this needs to act differently on Windows

2022-01-21 20:08 UTC, sfc-gh-mkeller commented on test/integ/test_arrow_result.py
> +        type, conn_cnx, sql_text, row_count, col_count, eps=timedelta(microseconds=1)
As we talked about this, add a Jira in the code here that describes fixing the JSON implementation too

2022-01-25 04:45 UTC, sfc-gh-mkeller approved these changes
![](https://i.fluffy.cc/VKWgLLbr8ZGc8Gs0b6Hm8wb5xQGmlbwR.gif)

2022-02-04 18:41 UTC, sfc-gh-mkeller commented
recheck

2022-02-04 22:59 UTC, sfc-gh-jbahk commented
I have read the CLA Document and I hereby sign the CLA

2022-04-12 02:18 UTC, merged