SNOW-532795: Bumped up PythonConnector PATCH version from 2.7.2 to 2.…
snowflakedb/snowflake-connector-python pull request #1033
Opened 2022-01-19 21:22 UTC by sfc-gh-kdama

@noreview - This is an automated process. No review is required

Co-authored-by: Jenkins User <snowflake-provisioner>

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #NNNN

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

2022-01-19 22:34 UTC, sfc-gh-kwagner commented on DESCRIPTION.md
> +   - Update requirements files Update numpy requirement from <1.22.0 to <1.23.0
Can we add this line:

"Add the ability to auto-create a table when writing a pandas DataFrame to a Snowflake table"

2022-01-19 22:34 UTC, sfc-gh-kwagner approved these changes
LGTM other than minor comment

2022-01-20 18:59 UTC, sfc-gh-mkeller requested changes
The lines that I removed are administrative, or non important for strictly users of the library

2022-01-20 18:59 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
> +   - shifted package metadata from setup.py to setup.cfg
```suggestion
```

2022-01-20 18:59 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
> +   - Add Timezone to Timestamp_TZ
```suggestion
   - Fixed a bug where timezone was missing from retrieved Timestamp_TZ columns
```

2022-01-20 18:59 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
> +   - Fix Storage Credential Error
```suggestion
   - Fixed a bug where a long running PUT/GET command could hit a Storage Credential Error while renewing credentials
```

2022-01-20 18:59 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
> +   - fix py.typed not being included in wheels
```suggestion
   - Fixed a bug where py.typed was not being included in our release wheels
```

2022-01-20 18:59 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
> +   - Update CODEOWNERS
```suggestion
```

2022-01-20 18:59 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
> +   - fix long description rendering for PyPi
```suggestion
   - Fixed rendering of our long description for PyPi
```

2022-01-20 18:59 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
> +   - handling no sms case for DUO
```suggestion
   - Fixed a bug where DUO authentication ran into errors if sms authentication was disabled for the user
```

2022-01-20 18:59 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
> +   - Update requirements files Update numpy requirement from <1.22.0 to <1.23.0
```suggestion
   - Bumped the maximum dependency version of numpy from <1.22.0 to <1.23.0
```

2022-01-20 18:59 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
> +   - Add GET Empty File Handling
```suggestion
   - Improved the error message that is encountered when running GET for a non-existing file
```

2022-01-20 18:59 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
> +   - Negative Numbers Mangled for arrow_number_to_decimal
```suggestion
   - Fixed a bug where negative numbers were mangled when fetched with the connection parameter arrow_number_to_decimal
```

2022-01-20 19:15 UTC, sfc-gh-mkeller approved these changes
![](https://i.fluffy.cc/4pzS922wdxxZ5qdZCFwLRs2pqg46hPnc.gif)

2022-01-20 19:17 UTC, merged