SNOW-507942 handle s3 accelerate configuration correctly
snowflakedb/snowflake-connector-python pull request #1088
Opened 2022-04-06 22:08 UTC by sfc-gh-cshi

A test is added to make sure right endpoint is used according to accelerate configuration

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #NNNN

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

2022-04-07 21:51 UTC, sfc-gh-cshi commented
I have read the CLA Document and I hereby sign the CLA

2022-04-28 19:14 UTC, sfc-gh-mkeller requested changes

2022-04-28 19:14 UTC, sfc-gh-mkeller commented on test/integ/test_put_get_user_stage.py
> +    """[s3] Puts and Gets Small Data via User Stage."""
This has to be the first thing in the function to be considered a doc-string, right now it's just a string constant that nothing points to

2022-04-28 19:14 UTC, sfc-gh-mkeller commented on test/integ/test_put_get_user_stage.py
> +    if is_public_test or "AWS_ACCESS_KEY_ID" not in os.environ:
I think you can just [tag the test as an internal test](https://github.com/snowflakedb/snowflake-connector-python/blob/f2f7e6f35a162484328399c8a50a5015825a5573/test/integ/test_cursor_binding.py#L139) to achieve the same thing

2022-04-28 19:14 UTC, sfc-gh-mkeller commented on test/unit/test_s3_util.py
> +        self: SnowflakeS3RestClient, use_accelerate_endpoint: bool = None
```suggestion
        self: SnowflakeS3RestClient,
        use_accelerate_endpoint: bool | None = None,
```

2022-04-29 22:21 UTC, sfc-gh-mkeller approved these changes

2022-05-12 20:06 UTC, merged