update to test_util.py
snowflakedb/snowflake-connector-python pull request #1164
Opened 2022-06-13 20:26 UTC by dylanbstorey

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #1163

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

  Updating the behaviour to provide an incredibly unlikely default value as an argument to `os.getenv` and then using the presence of that value to determine if `JENKINS_HOME` is set in the environment.

2022-06-13 20:28 UTC, dylanbstorey commented
recheck

2022-06-13 20:33 UTC, dylanbstorey commented
recheck

2022-07-25 22:22 UTC, sfc-gh-mkeller requested changes
I'm sorry, could you please explain how this solves your issue?
To me:
`os.getenv("JENKINS_HOME") is not None`
and
`os.getenv("JENKINS_HOME", JENKINS_HOME_DEFAULT_RETURN_VALUE) is not JENKINS_HOME_DEFAULT_RETURN_VALUE`
does the same thing.

If you overwrite `os.getenv` then its going to trigger both. Maybe something like this would be better?
```
RUNNING_ON_JENKINS = "JENKINS_HOME" in os.environ
```

2022-07-25 22:22 UTC, sfc-gh-mkeller commented on src/snowflake/connector/test_util.py
> +RUNNING_ON_JENKINS = os.getenv("JENKINS_HOME", JENKINS_HOME_DEFAULT_RETURN_VALUE) is not JENKINS_HOME_DEFAULT_RETURN_VALUE
You usually want to test equality of strings with `==`, or `!=` not with `is`.
```suggestion
RUNNING_ON_JENKINS = os.getenv("JENKINS_HOME", JENKINS_HOME_DEFAULT_RETURN_VALUE) != JENKINS_HOME_DEFAULT_RETURN_VALUE
```

2022-07-25 22:22 UTC, sfc-gh-mkeller commented on src/snowflake/connector/test_util.py
> +JENKINS_HOME_DEFAULT_RETURN_VALUE= '$!$@46217d2d-1000-40b2-b4e5-9fdbab719c7c'
Formatting
```suggestion
JENKINS_HOME_DEFAULT_RETURN_VALUE = '$!$@46217d2d-1000-40b2-b4e5-9fdbab719c7c'
```

2022-12-27 15:50 UTC, closed without merging