SNOW-460809 Attempt to add INFO level logging message regarding first chunk rowcount
snowflakedb/snowflake-connector-python pull request #1249
Opened 2022-09-14 00:04 UTC by sfc-gh-heshah

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes [SNOW-460809 Improve logging to log explicit how many rows were embedded in the Snowflake query response](https://snowflakecomputing.atlassian.net/browse/SNOW-460809)

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [x] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

Added `INFO` level logging message in `_init_result_and_meta` to retrieve the first chunk's rowcount if the query was not `is_dml` or `is_file_transfer`

2022-09-14 00:08 UTC, sfc-gh-heshah commented
I have read the CLA Document and I hereby sign the CLA. recheck

2022-09-14 00:10 UTC, sfc-gh-heshah commented
recheck

2022-09-19 21:23 UTC, sfc-gh-mkeller requested changes
Should we add a test, a unit test with (caplog)[https://docs.pytest.org/en/7.1.x/how-to/logging.html#caplog-fixture] should suffice

2022-09-22 20:09 UTC, sfc-gh-mkeller requested changes

2022-09-22 20:09 UTC, sfc-gh-mkeller commented on test/integ/test_cursor.py
> +                "(98765),(65432)".format(name=db_parameters["name"])
You shouldn't be using `db_parameters["name"]` instead please use the name randomizer. One example in this file: `random_string(5, "test_describe_")`

2022-09-22 20:09 UTC, sfc-gh-mkeller commented on test/integ/test_cursor.py
> +            assert "Number of results in first chunk: 3" in caplog.text
Instead of adding a brand new test, could we add this to an already existing test?

2022-09-22 22:52 UTC, sfc-gh-mkeller approved these changes
:ship: :ship:

2022-09-22 23:14 UTC, merged