SNOW-664933 Fix write_pandas with empty dataframe
snowflakedb/snowflake-connector-python pull request #1261
Opened 2022-09-27 20:41 UTC by sfc-gh-stan

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #SNOW-664933

2. Fill out the following pre-review checklist:

   - [x] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

  `write_pandas` used to raise `ValueError` when we attempt to write a dataframe with no rows, this is caused by `chunk_helper` attempting to generate chunks of 0 rows (`for i in range(0, len(lst), n):`). With this code change, we will just generate one chunk when the dataframe has fewer rows than the chunk size, which includes the special case of 0 rows.

2022-09-27 20:45 UTC, sfc-gh-stan commented on test/integ/pandas/test_pandas_tools.py
> +def test_empty_dataframe_auto_create_table_write_pandas(
The test name seems redundant, the issue we fix is irrelevant to `auto_create_table`.

2022-09-28 20:28 UTC, sfc-gh-sfan approved these changes
LGTM. Can you also port this to sp connector?

2022-09-28 20:56 UTC, sfc-gh-mkeller requested changes

2022-09-28 20:56 UTC, sfc-gh-mkeller commented on src/snowflake/connector/pandas_tools.py
> +        return
So it worked for shorter lists already:
```
>>> list(chunk_helper([1, 2], 3))
[(0, [1, 2])]
```
There's only one case the original function didn't work for and so this is more explicit:
```suggestion
    if n == len(lst):
        yield 0, lst
        return
```

2022-09-29 00:13 UTC, sfc-gh-mkeller approved these changes
:ship: :ship:

2022-09-29 00:13 UTC, sfc-gh-mkeller commented on test/integ/pandas/test_pandas_tools.py
> +            cnx.execute_string(f"DROP TABLE IF EXISTS {table_name}")
No need to call that helper fn (execute is enough), also if we used a temp table then this wouldn't be necessary at all.
```suggestion
            cnx.execute(f"DROP TABLE IF EXISTS {table_name}")
```

2022-09-29 00:13 UTC, sfc-gh-mkeller commented on test/integ/pandas/test_pandas_tools.py
> +                cnx, df, table_name, auto_create_table=True
We could use a temp table for this:
```suggestion
                cnx, df, table_name, auto_create_table=True, table_type="temp",
```

2022-09-29 19:02 UTC, merged