SNOW-680774 Check CLIENT_LOG_DIR_PATH_DOCKER for ENABLE_TELEMETRY_LOG
snowflakedb/snowflake-connector-python pull request #1288
Opened 2022-10-20 23:39 UTC by sfc-gh-sfan

Description

test_util is supposed to only be used by snowflake regression test, but currently it runs for all Jenkins linux hosts, which is not desired. A quick fix is to also check CLIENT_LOG_DIR_PATH_DOCKER, which presumbly is not used by most customers if not all.

Testing

existing tests

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #NNNN

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

2022-10-21 17:51 UTC, sfc-gh-mkeller requested changes

2022-10-21 20:30 UTC, sfc-gh-sfan commented on src/snowflake/connector/test_util.py
> +HAS_REGRESSION_TEST_LOG_DIR = os.getenv("CLIENT_LOG_DIR_PATH_DOCKER") is not None
I'm going to do the second one, but also change `REGRESSION_TEST_LOG_DIR is not None` to `REGRESSION_TEST_LOG_DIR`. An empty string does not make sense either :)

2022-10-21 23:12 UTC, sfc-gh-heshah approved these changes

2022-10-24 16:52 UTC, sfc-gh-sfan commented
The FIPS test failures are likely unrelated:

```
FAILED test/unit/test_ocsp.py::test_ocsp - AttributeError: 'UnsupportedAlgori...
FAILED test/unit/test_ocsp.py::test_ocsp_wo_cache_server - AttributeError: 'U...
FAILED test/unit/test_ocsp.py::test_ocsp_wo_cache_file - AttributeError: 'Uns...
FAILED test/unit/test_ocsp.py::test_ocsp_by_post_method - AttributeError: 'Un...
FAILED test/unit/test_ocsp.py::test_ocsp_with_file_cache - AttributeError: 'U...
FAILED test/unit/test_ocsp.py::test_ocsp_with_bogus_cache_files - AttributeEr...
FAILED test/unit/test_ocsp.py::test_ocsp_with_outdated_cache - AttributeError...
FAILED test/unit/test_ocsp.py::test_ocsp_cache_merge - AttributeError: 'Unsup...
```

2022-10-24 16:52 UTC, merged