SNOW-683718: Bumped up PythonConnector PATCH version from 2.8.0 to 2.8.1
snowflakedb/snowflake-connector-python pull request #1303
Opened 2022-10-27 21:27 UTC by sfc-gh-kdama

@noreview - This is an automated process. No review is required

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #NNNN

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

2022-10-27 22:00 UTC, sfc-gh-mkeller requested changes

2022-10-27 22:00 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
>  - v2.8.0(September 27,2022)
```suggestion
- v2.8.1(October 30,2022)
```

2022-10-27 22:00 UTC, sfc-gh-mkeller commented on DESCRIPTION.md
> +- v2.8.1(October 30,2022)
```suggestion
- v2.8.0(September 27,2022)
```

2022-10-27 22:06 UTC, sfc-gh-mkeller approved these changes
:ship: :ship:

2022-11-01 20:01 UTC, sfc-gh-jdu commented
Please mention the version bump for pandas as well. https://github.com/snowflakedb/snowflake-connector-python/commit/e36802e8da82225c1460871e94fcf60c8e247123

2022-11-01 21:04 UTC, merged