SNOW-676736: get file results in change of file permissions does not inherit parent folder permission
snowflakedb/snowflake-connector-python pull request #1338
Opened 2022-11-18 18:09 UTC by sfc-gh-aling

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #SNOW-676736

2. Fill out the following pre-review checklist:

   - [x] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

mkstemp creates a temporary file in the most secure manner possible -- which is only given permission to the current user, not to `group` or `other` which is not expected.

change to use `open` which will inherit the default file permission.

2022-11-21 20:08 UTC, sfc-gh-mkeller requested changes

2022-11-22 16:45 UTC, sfc-gh-aling commented on src/snowflake/connector/encryption_util.py
> +            with open(temp_output_file, "wb") as outfile:
emmm, I tested and found that `open` will just overwrite the existing file.

are you talking about using the `os.open` instead of the `io.open`?

2022-11-22 19:17 UTC, sfc-gh-aling commented on test/integ/test_put_get.py
> +            assert oct(os.stat(test_file).st_mode)[-3:] == oct(438 & ~default_mask)[-3:]
```suggestion
            assert oct(os.stat(test_file).st_mode)[-3:] == oct(0o666 & ~default_mask)[-3:]
```

2022-11-22 19:17 UTC, sfc-gh-aling commented on test/integ/test_put_get.py
> +            # 438 Decimal  == 666 Octal, files by default are given the permission 644 (Octal)
```suggestion
            # files by default are given the permission 644 (Octal)
```

2022-11-22 19:17 UTC, sfc-gh-mkeller approved these changes
:ship: :ship:

2022-11-22 22:33 UTC, merged