fix: type ResultMetaData fields as optional
snowflakedb/snowflake-connector-python pull request #1424
Opened 2023-02-05 06:43 UTC by tekumara

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #1423

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   type ResultMetaData fields as optional where they can be `None`

2023-03-13 02:33 UTC, tekumara commented
@sfc-gh-mkeller would you be able to take a look at this? 🙏

2023-04-05 21:18 UTC, sfc-gh-jdu approved these changes

2023-04-11 16:53 UTC, sfc-gh-mkeller requested changes

2023-04-11 16:53 UTC, sfc-gh-mkeller commented on src/snowflake/connector/cursor.py
> +    scale: Optional[int]
We should be using future annotations
```suggestion
    display_size: int | None
    internal_size: int | None
    precision: int | None
    scale: int | None
```

2023-05-07 05:46 UTC, tekumara commented
@sfc-gh-mkeller please see the changes I've made above

2023-05-09 17:46 UTC, sfc-gh-mkeller approved these changes
:ship: :ship:

2023-05-09 17:47 UTC, merged