SNOW-1763673 Python3.13 support
snowflakedb/snowflake-connector-python pull request #2105
Opened 2024-11-13 04:18 UTC by sfc-gh-mkeller

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes SNOW-1763673

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   These new versions usually need no code-changes. They should just work on new Python versions. I also took this opportunity to update pre-commit hooks and fix all files.
4. (Optional) PR for stored-proc connector:

2025-03-26 15:40 UTC, sfc-gh-pbulawa requested changes

2025-03-26 15:40 UTC, sfc-gh-pbulawa commented on Jenkinsfile
> +          'Test Python 38 OldDriver': { build job: 'RT-PyConnector38-OldDriver-PC',parameters: params},
Why do we test 3.8 here?

2025-03-26 15:40 UTC, sfc-gh-pbulawa commented on ci/docker/connector_test/Dockerfile
> +ENV PATH="${PATH}:/opt/python/cp37-cp37m/bin:/opt/python/cp38-cp38/bin:/opt/python/cp39-cp39/bin:/opt/python/cp310-cp310/bin:/opt/python/cp311-cp311/bin:/opt/python/cp312-cp312/bin:/opt/python/cp313-
Shouldn't only >cp39 be here?

2025-03-26 18:27 UTC, sfc-gh-fpawlowski commented on ci/docker/connector_test/Dockerfile
> +ENV PATH="${PATH}:/opt/python/cp37-cp37m/bin:/opt/python/cp38-cp38/bin:/opt/python/cp39-cp39/bin:/opt/python/cp310-cp310/bin:/opt/python/cp311-cp311/bin:/opt/python/cp312-cp312/bin:/opt/python/cp313-
I actually noticed that this is obsolete - PATH already points at the appropriate Python version - latest jobs were successful without it.

2025-03-27 08:33 UTC, sfc-gh-pbulawa approved these changes

2025-03-27 11:50 UTC, sfc-gh-mmishchenko requested changes
Is there a chance we could leave nanoarrow part untouched?

2025-03-27 15:53 UTC, sfc-gh-fpawlowski commented on test/integ/test_arrow_result.py
> -        "NUMBER": [numpy.NAN, 1.0, 2.0, 3.0],
Theoretically numpy supports both numpy.nan and numpy.NAN (they are aliases for the same thing).
 
I think need for this change was caused by increasing of numpy version.
Without it 'Test FIPS linux-3.9-aws' fails with the below error.
However I am not sure if it was a bug, since its just in our tests on numpy level.

_______________ ERROR collecting test/integ/test_arrow_result.py _______________
test/integ/test_arrow_result.py:119: in <module>
    "NUMBER": [numpy.NAN, 1.0, 2.0, 3.0],
../fips_env/lib64/python3.9/site-packages/numpy/__init__.py:410: in __getattr__
    raise AttributeError("module {!r} has no attribute "
E   AttributeError: module 'numpy' has no attribute 'NAN'

2025-03-27 16:17 UTC, sfc-gh-fpawlowski commented on src/snowflake/connector/converter.py
> +        return bool(value)
I think it was added in the original PR to mitigate some issues we no longer face. Removed it, since Jobs are successful without it.

2025-03-27 16:39 UTC, sfc-gh-mmishchenko approved these changes

2025-04-02 11:11 UTC, closed without merging

2025-04-02 11:12 UTC, sfc-gh-fpawlowski commented
Merged in branch: https://github.com/snowflakedb/snowflake-connector-python/pull/2239