[WIP]SNOW-135960: add basic tests for lambda
snowflakedb/snowflake-connector-python pull request #465
Opened 2020-10-05 23:41 UTC by sfc-gh-sbasavana

2020-10-06 19:28 UTC, sfc-gh-kwagner approved these changes
LGTM, I'll let Mark review the tox file changes since I'm still new to tox

2020-10-06 19:49 UTC, sfc-gh-stakeda commented
The test itself looks good. You'll need to add a set up script that:
- Create a Lambda package
- Deploy the package to the lambda in sfcdev
- Kick off the lambda
- Get the results

The tests should be runnable only in the Jenkins jobs.

2020-10-06 20:11 UTC, sfc-gh-sbasavana commented
> The test itself looks good. You'll need to add a set up script that:
> 
>     * Create a Lambda package
> 
>     * Deploy the package to the lambda in sfcdev
> 
>     * Kick off the lambda
> 
>     * Get the results
> 
> 
> The tests should be runnable only in the Jenkins jobs.

@sfc-gh-stakeda Yes, I have deployed lambda to sfctest for testing.  I'll get it deployed to sfc-dev once everything is ready.  Lambda gets invoked by the new jenkins job  as part of PR build and test job. Lambda downloads the build artifact from S3(uploaded by https://github.com/snowflakedb/snowflake-connector-python/blob/adcfdfe401b965be6847e5b47fd25481552fee3c/Jenkinsfile#L10-L27)  and runs these lambda tests against that build. Jenkins job is yet to be set up.

2020-10-06 23:21 UTC, sfc-gh-mkeller requested changes
Please change that one thing, otherwise it looks good!

2020-10-06 23:32 UTC, sfc-gh-sbasavana commented
> Please change that one thing, otherwise it looks good!

Done, thanks @sfc-gh-mkeller

2020-10-07 16:54 UTC, sfc-gh-mkeller approved these changes
🚢 🚢

2020-10-07 16:56 UTC, merged