SNOW-270946 Progress percentage computation to handle the case when f…
snowflakedb/snowflake-connector-python pull request #628
Opened 2021-02-16 20:46 UTC by sfc-gh-cshi

…ile size is zero

2021-02-18 18:42 UTC, sfc-gh-kwagner approved these changes

2021-02-18 19:28 UTC, sfc-gh-mkeller requested changes

2021-02-18 19:28 UTC, sfc-gh-mkeller commented on test/unit/test_put_get.py
> +    func_callback(1)
Check out [tmp_path fixture](https://docs.pytest.org/en/stable/tmpdir.html#the-tmp-path-fixture), it'll cut out a bunch of your code. Also please be aware of our existing type hints. The percentage classes expect a `str` path.
```suggestion
def test_percentage(tmp_path):
    """Tests for raise_put_get_error flag (now turned on by default) in SnowflakeFileTransferAgent."""
    file = tmp_path / 'zero_file1'
    file.touch()
    func_callback = SnowflakeS3ProgressPercentage(str(file), 0)
    func_callback(1)

    func_callback = SnowflakeAzureProgressPercentage(str(file), 0)
    func_callback(1)
```

2021-02-18 19:28 UTC, sfc-gh-mkeller commented on src/snowflake/connector/file_transfer_agent.py
> +def percent(seen_so_far, size):
Please verify these
```suggestion
def percent(seen_so_far:int , size: float) -> float:
```

2021-02-23 18:54 UTC, sfc-gh-mkeller requested changes

2021-02-23 18:54 UTC, sfc-gh-mkeller commented on test/unit/test_put_get.py
> +    Path(file_path).touch()
Please take a look at https://docs.pytest.org/en/stable/tmpdir.html `tmpdir` and `tmp_path` are not the same.
```suggestion
def test_percentage(tmp_path):
    """Tests for ProgressPercentage classes."""
    assert 1.0 == percent(0, 0)
    assert 1.0 == percent(20, 0)
    assert 1.0 == percent(40, 20)
    assert 0.5 == percent(14, 28)

    file_path = tmpdir / 'zero_file1'
```

2021-02-27 02:37 UTC, sfc-gh-mkeller requested changes

2021-02-27 02:37 UTC, sfc-gh-mkeller commented on src/snowflake/connector/file_transfer_agent.py
> +                percentage = percent(self._seen_so_far, self._size)
`self._size` is initialized as `float(filesize)` so you are not respecting the type hints of `percent`

2021-02-27 05:20 UTC, sfc-gh-mkeller approved these changes
🚢 🚢

2021-02-27 07:19 UTC, merged