SNOW-357321 Experiemental support for CI on linux of new architecture
snowflakedb/snowflake-connector-python pull request #731
Opened 2021-06-01 05:40 UTC by sfc-gh-cshi

This PR is basically moving Michael Dionne's change in ci-testing branch to 'ci/experimental' directory, to use right docker image. some other changes was just to make this directory change works.

2021-09-09 19:23 UTC, sfc-gh-cshi commented on ci/experimental/docker/Dockerfile
> +ARG BASE_IMAGE=quay.io/pypa/manylinux2014_aarch64
change to aarch64 docker image

2021-09-10 00:47 UTC, sfc-gh-mkeller requested changes

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/build_docker.sh
> +CONNECTOR_DIR="$(dirname "$( dirname "${THIS_DIR}")")"
Just looks a bit neater when the constants are all defined at the beginning in 1 block
```suggestion
CONNECTOR_DIR="$(dirname "$( dirname "${THIS_DIR}")")"
source $THIS_DIR/set_base_image.sh
```

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/build_docker.sh
> +echo "conndir= $CONNECTOR_DIR, thisdir=$THIS_DIR"
I don't think this adds any value, we use these constants everywhere, if they were wrong a lot of things would be broken.
I think we don't need to log them anymore

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/build_docker.sh
> +CONTAINER_NAME=build_pyconnector
Wouldn't this clash with the other non aarch docker image?
```suggestion
CONTAINER_NAME="build_pyconnector_aarch"
```

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/build_docker.sh
> +mkdir -p $CONNECTOR_DIR/dist
This fails if the dist directory already exists, there's a similar code snippet in `build_linux.sh`

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/docker/connector_build/Dockerfile
> +# We use manylinux1 base image because pyarrow_manylinux2010 has a bug and wheel failed to be audited
I think this file could go straight into `ci/docker/connector_build_aarch/Dockerfile`

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/docker/Dockerfile
> +# We use manylinux1 base image because pyarrow_manylinux2010 has a bug and wheel failed to be audited
I think this file is the same as `ci/experimental/docker/connector_build/Dockerfile` I think we don't need this

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/docker/connector_build/scripts/entrypoint.sh
> +#!/bin/bash
Instead of copying this file even more times, could we set soft links instead?
Could you look whether this is an option in git?

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/docker/connector_build/Dockerfile
> +# We use manylinux1 base image because pyarrow_manylinux2010 has a bug and wheel failed to be audited
I think this comment isn't true anymore
```suggestion
```

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/docker/connector_test/Dockerfile
> +# We use manylinux1 base image because pyarrow_manylinux2010 has a bug and wheel failed to be audited
This isn't true anymore
```suggestion
```

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/docker/connector_test/Dockerfile
> +ARG BASE_IMAGE
There's no default here, is that on purpose?

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/docker/connector_test/Dockerfile
> +# We use manylinux1 base image because pyarrow_manylinux2010 has a bug and wheel failed to be audited
Again, I think this could straight into `ci/docker/connector_test_aarch/Dockerfile`

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/docker/connector_test_fips/Dockerfile
> +FROM centos:7
I think this could move straight into `ci/docker/connector_test_fips_aarch`

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/docker/scripts/entrypoint.sh
> +#!/bin/bash
Please don't add `docker/scripts` directory, this script is in each of the docker directories already

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/set_base_image.sh
> +#!/bin/bash -e
We could get around copying this by moving the `ci/experimental/docker` to `ci/docker` as I mentioned already

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/test_docker.sh
> +#!/bin/bash -e
We should be able to reuse the already existing version of this

2021-09-10 00:47 UTC, sfc-gh-mkeller commented on ci/experimental/test_linux.sh
> +#!/bin/bash -e
Please, let's instead make `ci/test_linux.sh` work with aarch rather than copying so many shell scripts around

2021-09-14 22:33 UTC, closed without merging

2021-09-14 22:34 UTC, sfc-gh-cshi commented
Will open a new PR for this.