SNOW-368531 Fix `executemany` insert qmarks behaviour
snowflakedb/snowflake-connector-python pull request #796
Opened 2021-07-19 15:44 UTC by sfc-gh-kzaveri

This PR addresses changes requested in [SNOW-368531](https://snowflakecomputing.atlassian.net/browse/SNOW-368531)/ [GH Issue](https://github.com/snowflakedb/snowflake-connector-python/issues/750).

Our behavior when resolving the "type" of value had a bug. The best way to illustrate this would be with an example.

When using `executemany` to insert values, you would use a command such as this:

```python
    cursor.executemany(
        'INSERT INTO date_test (birth_date) values (?)',
        [[datetime.date(1969, 2, 7)],[datetime.date(1969, 1, 1)]]
    )
```
The `executemany` function would then transform the values in to a list like this ([see this](https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/cursor.py#L985)) :
  ```python 

[ datetime.date(1969, 2, 7), datetime.date(1969, 1, 1) ] 

```

We would then determine the corresponding "snowflake type" for this list. [Lists are type "TEXT"](https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/converter.py#L59) and thus when inserting these datetimes, Snowflake would interpret the epochs as "TEXT" which leads to the invalid dates appearing in the DB.

To fix this, I have set the "snowflake type" to  "TEXT" by default. However, if all of the values of the list have a certain type, say "DATE" in this case, we would update the "snowflake type" to "DATE" - which leads to a valid insert. 

Furthermore, users can now use Tuples to specify exactly which type they would like.
For example, they may do this:
```python
    cursor.executemany(
        'INSERT INTO date_test (birth_date) values (?)',
        [
               [ ("DATE", datetime.date(1969, 2, 7)) ],
               [ ("DATE", datetime.date(1969, 1, 1)) ]
        ]
    )
```

2021-07-19 15:45 UTC, sfc-gh-kzaveri commented on src/snowflake/connector/connection.py
> +                    snowflake_type = first_type
This is to set `snowflake_type` to "LIST", then it obtains the type and binding for each parameter in the list.
If all types are the same -> update snowflake type.

2021-08-10 19:03 UTC, sfc-gh-mkeller requested changes

2021-08-10 19:03 UTC, sfc-gh-mkeller commented on src/snowflake/connector/connection.py
> +        TypeAndBinding = namedtuple("TypeAndBinding", ["type", "binding"])
Move out of this function and make sure to update the return type.
Also check if we could use this and `get_snowflake_type_and_binding` in any other places, like `_process_params`

2021-08-16 21:02 UTC, sfc-gh-mkeller requested changes

2021-08-16 21:02 UTC, sfc-gh-mkeller commented on src/snowflake/connector/connection.py
> +            )
I have the tiniest nitpick:
The return statement can be moved out from the if-else clauses this way:
```suggestion
            snowflake_type, v = v
        else:
            snowflake_type = self.converter.snowflake_type(v)
            if snowflake_type is None:
                Error.errorhandler_wrapper(
                    self,
                    cursor,
                    ProgrammingError,
                    {
                        "msg": "Python data type [{}] cannot be "
                        "automatically mapped to Snowflake data "
                        "type. Specify the snowflake data type "
                        "explicitly.".format(v.__class__.__name__.lower()),
                        "errno": ER_NOT_IMPLICITY_SNOWFLAKE_DATATYPE,
                    },
                )
        return TypeAndBinding(
            snowflake_type,
            self.converter.to_snowflake_bindings(snowflake_type, v),
        )
```

2021-08-16 21:03 UTC, sfc-gh-mkeller commented
Love the way you used the `map` with `partial` 👍

2021-08-16 23:37 UTC, sfc-gh-mkeller approved these changes
🚢 🚢

2021-08-18 15:24 UTC, sfc-gh-kzaveri commented
I verified that this issue: https://snowflakecomputing.atlassian.net/browse/SNOW-303368 is also solved by this change.
See:
https://snowflakecomputing.atlassian.net/browse/SNOW-303368?focusedCommentId=1825333

2021-08-18 23:49 UTC, merged