Support build for other archtecture on linux
snowflakedb/snowflake-connector-python pull request #869
Opened 2021-09-14 06:43 UTC by sfc-gh-cshi

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #NNNN

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

2021-09-30 00:43 UTC, sfc-gh-stakeda commented
LGTM

2021-09-30 22:59 UTC, sfc-gh-kwagner approved these changes

2021-10-01 18:49 UTC, sfc-gh-mkeller requested changes

2021-10-01 18:49 UTC, sfc-gh-mkeller commented on ci/docker/connector_build/Dockerfile
> +ARG BASE_IMAGE
Please keep the default values
```suggestion
ARG BASE_IMAGE=quay.io/pypa/manylinux2010_x86_64
```

2021-10-01 18:49 UTC, sfc-gh-mkeller commented on ci/docker/connector_build/Dockerfile
> +ARG GOSU_URL
Default to old values
```suggestion
ARG GOSU_URL=https://github.com/tianon/gosu/releases/download/1.11/gosu-amd64
```

2021-10-01 18:49 UTC, sfc-gh-mkeller commented on ci/docker/connector_test/Dockerfile
> +ARG GOSU_URL
Keeping default values can make sure that we don't break downsstream project that might be using this Dockerfile
```suggestion
ARG GOSU_URL=https://github.com/tianon/gosu/releases/download/1.11/gosu-amd64
```

2021-10-04 16:59 UTC, sfc-gh-mkeller approved these changes
Thanks @sfc-gh-cshi , looks good!

2021-10-04 18:55 UTC, merged