SNOW-489676 Add Source Field to Telemetry
snowflakedb/snowflake-connector-python pull request #967
Opened 2021-11-15 21:14 UTC by sfc-gh-jbahk

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes SNOW-489676

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Adds "source" field to other telemetry field for parity with other connectors.

2021-11-15 21:22 UTC, sfc-gh-jbahk commented
New message result:
```
{
  "query_id": "01a05035-0403-0489-0000-0ca92e3ad102",
  "source": "PythonConnector",
  "type": "client_time_consume_first_result",
  "value": 15
}
```

2021-11-15 23:11 UTC, sfc-gh-azhan approved these changes
LGTM

2021-11-16 01:10 UTC, sfc-gh-mkeller requested changes

2021-11-16 01:10 UTC, sfc-gh-mkeller commented on src/snowflake/connector/errors.py
> +            telemetry_data[TelemetryField.KEY_SOURCE] = CLIENT_NAME
You should be able to overwrite this variable with an argument and when that's not given the do this as the default value

2021-11-16 01:10 UTC, sfc-gh-mkeller commented on src/snowflake/connector/telemetry.py
> +    KEY_SOURCE = "source"
This class should be an Enum

2021-11-18 19:13 UTC, sfc-gh-mkeller approved these changes

2021-11-19 07:06 UTC, merged