SNOW-474073 Add 3.10 Support
snowflakedb/snowflake-connector-python pull request #982
Opened 2021-11-19 07:03 UTC by sfc-gh-jbahk

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes SNOW-474073

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

2021-11-19 11:09 UTC, alexanderGerbik commented on .github/workflows/build_test.yml
> +        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
```suggestion
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
```
It seems that yaml parser treats `3.10` as float `3.1`, which has `"3.1"` string representation, which breaks the build. Don't forget to make the same changes further in this file.

It seems that `.github/workflows/create_req_files.yml` needs respective changes too.

2021-11-19 19:17 UTC, alexanderGerbik commented on .github/workflows/build_test.yml
> +          - version: 3.10
```suggestion
          - version: "3.10"
```

2021-11-30 20:00 UTC, HarryVeilleux commented
Any progress on this? Our team has a number of scripts stuck without 3.10 compatibility because of dependency on snowflake-connector.

2021-12-02 00:02 UTC, sfc-gh-mkeller requested changes

2021-12-02 00:02 UTC, sfc-gh-mkeller commented on .github/workflows/create_req_files.yml
> +        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
```suggestion
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
```

2021-12-02 00:02 UTC, sfc-gh-mkeller commented on .github/workflows/build_test.yml
> +        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
```suggestion
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
```

2021-12-02 00:02 UTC, sfc-gh-mkeller commented on .github/workflows/build_test.yml
> +        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]
```suggestion
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
```

2021-12-02 00:02 UTC, sfc-gh-mkeller commented on .github/workflows/build_test.yml
> +          - version: "3.10"
Update the previous ones too to be strings, please!

2021-12-02 00:04 UTC, sfc-gh-mkeller commented
@sfc-gh-jbahk maybe we should start by defining the Python 3.10 Jenkins test first.
Be aware that this might be blocked by SNOW-496969

2021-12-07 03:18 UTC, sfc-gh-mkeller approved these changes
This is good, but please only merge this once the Linux 310 test job is live, otherwise `pr-head` will be broken for every single PR

2021-12-10 00:06 UTC, merged